---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update-cache: yes
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: "Creates directory"
  file:
    path: /home/ubuntu/backend
    state: directory
- name: "Copy zip file"
  copy:
    src: "~/project/artifact.tar.gz"
    dest: "/home/ubuntu/web/artifact.tar.gz" 
- name: "extract"
  shell: |
    cd /home/ubuntu/backend
    tar -xzvf artifact.tar.gz
    ls -laR
- name: "run"
  shell: |
    npm install
    # pm2 stop default
    # pm2 start npm -- start
    npm start
